---
name: CI Pipeline

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!alpha'
      - '!dev'

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt
      
      - name: Lint
        run: |
          gixy service/config_modules/*.conf --output gixy-report.txt

      - name: Upload gixy report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: gixy-report
          path: gixy-report.txt
          if-no-files-found: warn
          retention-days: 30
      
      - name: Format
        run: |
          nginxfmt -v service/config_modules/*.conf &> nginxfmt-report.txt

      - name: Upload nginxfmt report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginxfmt-report
          path: nginxfmt-report.txt
          if-no-files-found: warn
          retention-days: 30
